# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2 
jobs:
   build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: yarn install
      - persist_to_workspace:
          root: ~/repo
          paths:
            - node_modules  
   test:
    working_directory: ~/repo
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: yarn install
      - run: npm test
      - persist_to_workspace:
          root: ~/repo
          paths:
            - node_modules
   android:
    working_directory: ~/repo/android
    docker:
      - image: circleci/android:api-23-node8-alpha
    steps:
      - checkout:
          path: ~/repo
      - attach_workspace:
          at: ~/repo
      - run: echo 'export TERM=xterm' >> $BASH_ENV
      - run: echo y | android update sdk --no-ui --all --filter "tools"
      - run: echo y | android update sdk --no-ui --all --filter "build-tools-23.0.2"
      - run: sudo chmod +x ./gradlew
      - run: bundle install 
      - run: bundle exec fastlane debugBuild 
      - store_artifacts:
          path: app/build/outputs/apk
          destination: apk
      
workflows:
  version: 2
  node-android:
    jobs:
    - build:
        filters:
            tags:
              ignore: /^testing
    - test:
        requires:
          - build
    - android:
        requires:
          - build

